-- ============================================================================================
-- PROPOSAL ONLY -- NOT part of the automatic migration set. Review, then apply by hand.
-- Gap DA-41 (security): today the policies on member_licence_applications and its children
-- ("manage own or anonymous ...", member_id IS NULL OR member_id = current_member_id()) let ANY
-- visitor holding the public anon key SELECT / UPDATE / DELETE EVERY anonymous application, its
-- answers (director phone numbers, e-mails, addresses, source-of-funds descriptions) and, via
-- the storage policy, its uploaded files (ID documents, certificates of good conduct).
--
-- Fix proposed: a per-application capability secret.
--   * member_licence_applications.access_token (uuid, random) is generated by the creating browser
--     (crypto.randomUUID()), sent in the INSERT and kept in that browser's localStorage. (It must be
--     client-generated: INSERT ... RETURNING is checked against the SELECT policy, which needs the
--     header, so the header has to be known before the row exists.)
--   * The Apply client then sends it on every request as the `x-application-token` header.
--     (src/app/apply/digital-lending already does this when the row carries access_token:
--     see TOKEN_KEY in digital-lending-wizard-client.tsx and createClient({headers}) in
--     src/lib/supabase/client.ts. Nothing changes for the app until this file is applied.)
--   * RLS compares the header with the row's token, so knowing/guessing an application id is no
--     longer enough, and anonymous rows can no longer be enumerated.
--
-- Caveats / things to decide before applying:
--   - Existing anonymous drafts (token generated by the default below) become inaccessible to
--     their browsers, which do not hold the token. Run this before real applicants exist, or
--     accept that they must start again.
--   - Payments / Insurance Apply use the same tables WITHOUT the header: applying this as-is
--     would lock them out. Either give those clients the same header, or add
--       `and application_key = 'digital_lending'` to the new predicates and keep the old policies
--     for the other application_key values until they are migrated.
--   - INSERT of an anonymous row stays open (WITH CHECK on member_id is null).
--   - The storage `licence-application-files` policy is changed in the same way (folder 1 = id).
-- ============================================================================================

alter table public.member_licence_applications
  add column if not exists access_token uuid not null default gen_random_uuid();

create or replace function public.da_request_token() returns text
language sql stable as $$
  select coalesce(current_setting('request.headers', true)::json ->> 'x-application-token', '')
$$;

-- Applications ---------------------------------------------------------------------------------
drop policy if exists "manage own or anonymous licence application" on public.member_licence_applications;
create policy "own application or anonymous with token" on public.member_licence_applications
  for all
  using (member_id = public.current_member_id()
         or (member_id is null and access_token::text = public.da_request_token()))
  with check (member_id = public.current_member_id()
              or member_id is null);

-- Children: item_state, files, reviews, regulator requests ---------------------------------------
do $$
declare t text; p record;
begin
  foreach t in array array['member_licence_application_item_state','member_licence_application_files',
                           'member_licence_application_reviews','member_licence_application_regulator_requests']
  loop
    for p in select policyname from pg_policies where schemaname='public' and tablename=t and policyname like 'manage own or anonymous%'
    loop
      execute format('drop policy %I on public.%I', p.policyname, t);
    end loop;
    execute format($f$create policy "own application or anonymous with token" on public.%I for all
      using (application_id in (select a.id from public.member_licence_applications a
                                where a.member_id = public.current_member_id()
                                   or (a.member_id is null and a.access_token::text = public.da_request_token())))
      with check (application_id in (select a.id from public.member_licence_applications a
                                where a.member_id = public.current_member_id()
                                   or (a.member_id is null and a.access_token::text = public.da_request_token())))$f$, t);
  end loop;
end $$;

-- Storage bucket ---------------------------------------------------------------------------------
drop policy if exists "manage own or anonymous application files (storage)" on storage.objects;
create policy "own application or anonymous with token (storage)" on storage.objects
  for all
  using (bucket_id = 'licence-application-files'
         and (storage.foldername(name))[1] in (
           select a.id::text from public.member_licence_applications a
           where a.member_id = public.current_member_id()
              or (a.member_id is null and a.access_token::text = public.da_request_token())))
  with check (bucket_id = 'licence-application-files'
         and (storage.foldername(name))[1] in (
           select a.id::text from public.member_licence_applications a
           where a.member_id = public.current_member_id()
              or (a.member_id is null and a.access_token::text = public.da_request_token())));
