-- Payments Apply (payments_nps): v7 content layer from the Beacon design (GUIDE / PRODUCT / CARD_NOTES / WORKSPACE_HIDDEN).
-- Idempotent data UPDATEs keyed on external_id. Requires 0201.
begin;
update licence_application_templates set
  card_title=$q$Minimum paid-up capital$q$, card_note=$q$Add evidence of the applicable minimum paid-up capital.$q$, short_cta=$q$Add capital evidence$q$,
  guidance_long=$q$The applicant should demonstrate that it holds at least the applicable minimum paid-up capital for the selected licence route. The evidence should support the amount held and should also allow the capital position, quality of capital, balance-sheet composition and growth plans to be assessed.$q$, deliverable=$q$Evidence supporting the applicable minimum paid-up capital and the applicant’s capital position.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(v), PDF p.7", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 23, PDF p.8", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}, {"text": "National Payment Systems (Amendment) Regulations, 2022 — Schedule 4, PDF pp.5–7", "url": "https://drive.google.com/file/d/1oozJCdTwoyvU_kRJHpiHBi_ZxWqG2sCY/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$capital$q$, product_config=$q${}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$B07$q$;
update licence_application_templates set
  card_title=$q$Company TIN & tax clearance$q$, card_note=$q$Enter the company TIN and upload the current tax-clearance certificate.$q$, short_cta=$q$Add tax details$q$,
  guidance_long=$q$The applicant should provide its Tax Identification Number and a current company tax-clearance certificate. The legal name and TIN on the tax evidence should be consistent with the applicant entity used throughout the application.$q$, deliverable=$q$Applicant company TIN and current company tax-clearance certificate.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(p), PDF p.6", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU Guidance on Licensing under the NPS Act, 2026 — Slide 11", "url": "https://docs.google.com/presentation/d/1xbFcGFaAGJhYlkWh_jSVuBhh59yZyR3B/edit?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$tin_tax$q$, product_config=$q${}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$B09$q$;
update licence_application_templates set
  card_title=$q$Finance Policy$q$, card_note=$q$Upload the Finance Policy.$q$, short_cta=$q$Upload policy$q$,
  guidance_long=$q$The licence application should include a Finance Policy. The policy should explain how the applicant manages its financial affairs and the controls governing financial transactions and reporting. A practical structure can cover the accounting process and systems, revenue and cost recognition, financial controls and approvals, reconciliations, financial reporting, the chart of accounts, assets and liabilities, and segregation of duties. Depending on the business model, it may also address purchasing, accounts payable, payroll and other relevant finance processes.$q$, deliverable=$q$Current Finance Policy.$q$,
  sources=$q$[{"text": "BoU Guidance on Licensing under the NPS Act, 2026 — Slide 13", "url": "https://docs.google.com/presentation/d/1xbFcGFaAGJhYlkWh_jSVuBhh59yZyR3B/edit?usp=drivesdk"}, {"text": "FITSPA NPS Compliance Guidance Tool, 2021 — Accounting policy and procedures, PDF pp.32–33", "url": "https://drive.google.com/file/d/1XwwpCy0nYblJcnwrYfu3AyI59YPwrU5m/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf,.rtf,.txt"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$B10$q$;
update licence_application_templates set
  card_title=$q$HR Policy$q$, card_note=$q$Upload the HR Policy.$q$, short_cta=$q$Upload policy$q$,
  guidance_long=$q$The licence application should include an HR Policy. A practical structure can cover HR governance and responsibilities, recruitment and appointment, conditions of employment, staff development, career development, performance evaluation, compensation, discipline, leave, termination and employee safety and security. The policy should reflect the applicant’s actual organisational structure and employment arrangements.$q$, deliverable=$q$Current HR Policy.$q$,
  sources=$q$[{"text": "BoU Guidance on Licensing under the NPS Act, 2026 — Slide 13", "url": "https://docs.google.com/presentation/d/1xbFcGFaAGJhYlkWh_jSVuBhh59yZyR3B/edit?usp=drivesdk"}, {"text": "FITSPA NPS Compliance Guidance Tool, 2021 — Human resources policy and procedures, PDF pp.40–41", "url": "https://drive.google.com/file/d/1XwwpCy0nYblJcnwrYfu3AyI59YPwrU5m/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf,.rtf,.txt"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$B11$q$;
update licence_application_templates set
  card_title=$q$Risk Management Framework$q$, card_note=$q$Upload the Risk Management Framework.$q$, short_cta=$q$Upload framework$q$,
  guidance_long=$q$The application should include a risk management framework appropriate to the proposed payment activities. The framework should identify the material risks affecting the business, explain how those risks are assessed and prioritised, assign responsibility for managing them, and describe the controls used to mitigate them. It should also explain how risks are monitored and reported, how significant issues are escalated, and how the framework connects with disaster recovery, cybersecurity and business continuity arrangements.$q$, deliverable=$q$Current Risk Management Framework.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(f), PDF p.5", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "National Payment Systems Regulations, 2021 — Reg. 32, PDF p.25", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "FITSPA NPS Compliance Guidance Tool, 2021 — Risk Management Framework, PDF p.45", "url": "https://drive.google.com/file/d/1XwwpCy0nYblJcnwrYfu3AyI59YPwrU5m/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf,.rtf,.txt"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$T01$q$;
update licence_application_templates set
  card_title=$q$Disaster Recovery Plan$q$, card_note=$q$Upload the Disaster Recovery Plan.$q$, short_cta=$q$Upload plan$q$,
  guidance_long=$q$The disaster-recovery plan should explain how critical technology, systems and data will be restored after a disruptive event. It should cover critical systems and data, backup and recovery arrangements, recovery responsibilities, alternate arrangements, testing and how weaknesses identified through testing are remediated. The plan should reflect the applicant’s actual technology architecture.$q$, deliverable=$q$Current Disaster Recovery Plan.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(f), PDF p.5", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 7, PDF p.5", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}, {"text": "FITSPA NPS Compliance Guidance Tool, 2021 — Business continuity guidance, PDF pp.46–48", "url": "https://drive.google.com/file/d/1XwwpCy0nYblJcnwrYfu3AyI59YPwrU5m/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf,.rtf,.txt"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$T02$q$;
update licence_application_templates set
  card_title=$q$Business Continuity Plan$q$, card_note=$q$Upload the Business Continuity Plan.$q$, short_cta=$q$Upload plan$q$,
  guidance_long=$q$The business-continuity plan should explain how important business services will continue or recover during severe disruption. A practical structure can identify important services and dependencies, tolerable disruption levels, the people, processes, technology, facilities and information needed to support them, testing of plausible scenarios, lessons from testing, and internal and external communications. Customer access and regulatory reporting should also be addressed where relevant.$q$, deliverable=$q$Current Business Continuity Plan.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(f), PDF p.5", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 7, PDF p.5", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}, {"text": "FITSPA NPS Compliance Guidance Tool, 2021 — Business continuity guidance, PDF pp.46–48", "url": "https://drive.google.com/file/d/1XwwpCy0nYblJcnwrYfu3AyI59YPwrU5m/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf,.rtf,.txt"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$T03$q$;
update licence_application_templates set
  card_title=$q$Cybersecurity plan / policy$q$, card_note=$q$Upload the cybersecurity plan or policy.$q$, short_cta=$q$Upload document$q$,
  guidance_long=$q$The cybersecurity plan or policy should explain how cyber risks to systems, assets, data and services are identified, protected against, detected, responded to and recovered from. It should cover access management, data protection, patching and vulnerability management, network architecture, email and browser security, and endpoint hardening. The Identify, Protect, Detect, Respond and Recover functions can be used as a practical organising structure.$q$, deliverable=$q$Current cybersecurity plan / policy.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(f), PDF p.5", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 7, PDF p.5", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}, {"text": "FITSPA NPS Compliance Guidance Tool, 2021 — Cybersecurity framework, PDF pp.49–51", "url": "https://drive.google.com/file/d/1XwwpCy0nYblJcnwrYfu3AyI59YPwrU5m/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf,.rtf,.txt"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$T04$q$;
update licence_application_templates set
  card_title=$q$Data protection & privacy$q$, card_note=$q$Upload the data-protection and privacy policy.$q$, short_cta=$q$Upload policy$q$,
  guidance_long=$q$The data-protection and privacy policy should explain how personal and customer data is collected, used, accessed, protected, retained, classified and disposed of. It should address confidentiality and encryption, data integrity, masking where relevant, retention, classification and access controls, and should align with the applicable data-protection obligations.$q$, deliverable=$q$Current data-protection and privacy policy.$q$,
  sources=$q$[{"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 7, PDF p.5", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}, {"text": "National Payment Systems Regulations, 2021 — Reg. 25(2), PDF p.22", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "National Payment Systems (Consumer Protection) Regulations, 2022 — Reg. 3(2), PDF p.5", "url": "https://drive.google.com/file/d/1I0n23-tnJSbwjLnT2mG1tioXWxpgIn8w/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf,.rtf,.txt"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$T05$q$;
update licence_application_templates set
  card_title=$q$IT policy & controls$q$, card_note=$q$Add the IT documents that cover the required control areas.$q$, short_cta=$q$Add IT documents$q$,
  guidance_long=$q$The IT policy and control documentation should cover the technology controls relevant to the applicant’s systems and operations. This includes IT asset inventory and maintenance, configuration and change management, identity and access management, data architecture and protection, patching and vulnerability management, network architecture, email and browser security, and endpoint security and hardening. These areas may be covered in one consolidated document or a set of documents, provided the coverage is clear.$q$, deliverable=$q$One or more current IT policy / control documents that collectively cover the applicable technology-control areas.$q$,
  sources=$q$[{"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 7, PDF p.5", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}, {"text": "BoU Guidance on Licensing under the NPS Act, 2026 — Slide 13", "url": "https://docs.google.com/presentation/d/1xbFcGFaAGJhYlkWh_jSVuBhh59yZyR3B/edit?usp=drivesdk"}, {"text": "FITSPA NPS Compliance Guidance Tool, 2021 — Information Security Policy, PDF pp.30–31", "url": "https://drive.google.com/file/d/1XwwpCy0nYblJcnwrYfu3AyI59YPwrU5m/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$it_controls$q$, product_config=$q${}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$T06$q$;
update licence_application_templates set
  card_title=$q$Penetration testing$q$, card_note=$q$Upload the penetration-test report and any required remediation evidence.$q$, short_cta=$q$Add penetration-test report$q$,
  guidance_long=$q$A pre-application penetration test should be completed for the electronic platform or system. The application should include the test report and should also show how material findings have been resolved or, where remediation is still in progress, how they are being managed and completed.$q$, deliverable=$q$Penetration-test report plus remediation evidence or status for material findings.$q$,
  sources=$q$[{"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 7, PDF p.5", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$pentest$q$, product_config=$q${}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$T07$q$;
update licence_application_templates set
  card_title=$q$NITA-U systems-licence / certification evidence$q$, card_note=$q$Upload the required NITA-U systems-licence or certification evidence.$q$, short_cta=$q$Upload evidence$q$,
  guidance_long=$q$Where the payment system or payment service operates on an electronic system or platform, the application should include the certified NITA-U systems-licence or certification evidence required for licensing. The evidence should be current and should clearly relate to the system or applicant for which the licence application is being made.$q$, deliverable=$q$Certified NITA-U systems-licence / certification evidence required for the electronic system or platform.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(q), PDF p.6", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 18, PDF p.7", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}, {"text": "BoU Guidance on Licensing under the NPS Act, 2026 — Slide 12", "url": "https://docs.google.com/presentation/d/1xbFcGFaAGJhYlkWh_jSVuBhh59yZyR3B/edit?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$upload$q$, product_config=$q${"accept": ".pdf,.png,.jpg,.jpeg"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$T08$q$;
update licence_application_templates set
  card_title=$q$Outsourcing arrangements$q$, card_note=$q$Record each material outsourcing arrangement and its agreement.$q$, short_cta=$q$Add arrangement$q$,
  guidance_long=$q$Each material outsourcing arrangement should be documented, including the service being outsourced, the service provider, the reason for outsourcing and the associated risks and controls. The governing contract or agreement should be attached, together with any supporting service-level or control documentation that is relevant.$q$, deliverable=$q$Record of each material outsourcing arrangement plus the governing contract / agreement and relevant supporting material.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(t), PDF p.6", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 21, PDF p.7", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}, {"text": "National Payment Systems Regulations, 2021 — Reg. 28(2), PDF pp.22–23", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$outsourcing$q$, product_config=$q${}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$T09$q$;
update licence_application_templates set
  card_title=$q$Participation in other payment systems$q$, card_note=$q$Record participation in other domestic or foreign payment systems.$q$, short_cta=$q$Add payment system$q$,
  guidance_long=$q$For each domestic or foreign payment system in which the applicant already participates or plans to participate, the application should explain the nature of the participation and the applicable participation rules. Evidence of admission or participation should be attached where it exists. If there is no planned or existing participation, that should be stated clearly.$q$, deliverable=$q$Participation details and supporting admission / rules evidence for each relevant payment system, or a confirmed 'none' response.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(u), PDF p.6", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 22, PDF p.8", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$payment_systems$q$, product_config=$q${}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$T10$q$;
update licence_application_templates set
  card_title=$q$Payment-system rules$q$, card_note=$q$Upload the payment-system rules or rulebook.$q$, short_cta=$q$Upload rules$q$,
  guidance_long=$q$The payment-system rules should govern how participants enter, operate within and exit the system. They should address admission, suspension and exclusion, participant rights and obligations, finality and irrevocability, execution and settlement, continuity arrangements, dispute resolution, fees and penalties, and the relevant contact or reporting arrangements.$q$, deliverable=$q$Current payment-system rules / rulebook.$q$,
  sources=$q$[{"text": "National Payment Systems Act, 2020 (Cap. 59) — s.11(1)–(2), PDF pp.11–12", "url": "https://drive.google.com/file/d/1TssAB7TOnkqpUjWWHs8dzWxteSlsU7AM/view?usp=drivesdk"}, {"text": "National Payment Systems Act, 2020 (Cap. 59) — s.11(2), PDF pp.11–12", "url": "https://drive.google.com/file/d/1TssAB7TOnkqpUjWWHs8dzWxteSlsU7AM/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf,.rtf,.txt"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$T11$q$;
update licence_application_templates set
  card_title=$q$AML/CFT Policy$q$, card_note=$q$Upload the AML/CFT Policy.$q$, short_cta=$q$Upload policy$q$,
  guidance_long=$q$The AML/CFT Policy should explain how the applicant prevents, identifies, monitors, escalates and reports money-laundering and terrorist-financing risks in its business. It should address governance, AML/CFT risk assessment, customer due diligence, transaction monitoring, suspicious-activity reporting, training and communication, and independent review or audit, with the level of detail reflecting the applicant’s products and risk profile.$q$, deliverable=$q$Current AML/CFT Policy.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(s), PDF p.6", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 20, PDF p.7", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}, {"text": "FITSPA NPS Compliance Guidance Tool, 2021 — AML/CFT guidance, PDF pp.36–39", "url": "https://drive.google.com/file/d/1XwwpCy0nYblJcnwrYfu3AyI59YPwrU5m/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf,.rtf,.txt"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$A01$q$;
update licence_application_templates set
  card_title=$q$Consumer Protection Policy$q$, card_note=$q$Upload the Consumer Protection Policy.$q$, short_cta=$q$Upload policy$q$,
  guidance_long=$q$The Consumer Protection Policy should set out how customer protection is governed and implemented across the business. It should address accountability and transparency, complaints and redress, staff and agent responsibilities and training, safeguards for consumer assets and data, fraud controls, information sharing, data-security risk assessment and the review or audit of consumer-protection arrangements.$q$, deliverable=$q$Current Consumer Protection Policy.$q$,
  sources=$q$[{"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 8, PDF pp.5–6", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}, {"text": "National Payment Systems (Consumer Protection) Regulations, 2022 — Reg. 3(1)–(2), PDF p.5", "url": "https://drive.google.com/file/d/1I0n23-tnJSbwjLnT2mG1tioXWxpgIn8w/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf,.rtf,.txt"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$A02$q$;
update licence_application_templates set
  card_title=$q$Customer disclosure, complaints & redress$q$, card_note=$q$Add the customer disclosure and complaints/redress documents.$q$, short_cta=$q$Add documents$q$,
  guidance_long=$q$The customer disclosure and complaints procedures should explain how customers receive clear information about the product, its key features, benefits, risks, prices and fees, and how complaints are received, acknowledged, investigated, escalated and resolved. The procedures should use clear and comprehensible language, provide accessible complaint channels, define timelines and record-keeping, and explain available redress.$q$, deliverable=$q$Current customer disclosure material and complaints / redress procedures. More than one document may be used.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(g), PDF p.5", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "National Payment Systems (Consumer Protection) Regulations, 2022 — Regs. 12–14, PDF pp.11–12", "url": "https://drive.google.com/file/d/1I0n23-tnJSbwjLnT2mG1tioXWxpgIn8w/view?usp=drivesdk"}, {"text": "National Payment Systems (Consumer Protection) Regulations, 2022 — Regs. 21–24 and Schedule, PDF pp.16–20", "url": "https://drive.google.com/file/d/1I0n23-tnJSbwjLnT2mG1tioXWxpgIn8w/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$multi_upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf,.rtf,.txt"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$A03$q$;
update licence_application_templates set
  card_title=$q$Customer agreement / terms$q$, card_note=$q$Upload the customer agreement or terms that apply to this licence route.$q$, short_cta=$q$Add agreement / terms$q$,
  guidance_long=$q$The customer agreement or terms should clearly state the contractual conditions governing the service and should be consistent with the product and pricing disclosures. For an electronic-money issuer, the application should include the customer-service agreement and customer fees. For a payment-instrument issuer, the terms and conditions of issuance should be provided. Customer-facing terms should clearly explain relevant features, risks, fees and conditions.$q$, deliverable=$q$Applicable customer agreement or terms: EMI customer-service agreement and fees, or payment-instrument terms and conditions, as applicable.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(y), PDF p.7", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "National Payment Systems Regulations, 2021 — Reg. 4(3)(d), PDF p.8", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "National Payment Systems (Consumer Protection) Regulations, 2022 — Regs. 12–14, PDF pp.11–12", "url": "https://drive.google.com/file/d/1I0n23-tnJSbwjLnT2mG1tioXWxpgIn8w/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$customer_terms$q$, product_config=$q${}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$A04$q$;
update licence_application_templates set
  card_title=$q$Pricing & fees$q$, card_note=$q$Upload the applicable pricing or fee document.$q$, short_cta=$q$Add pricing document$q$,
  guidance_long=$q$The pricing material should clearly explain what the customer pays and how the price or fee is determined. For a payment-instrument issuer, the pricing policy should identify the variables used to arrive at the price and the nature and amount of charges or fees. The pricing information should be consistent with the customer agreement, fee schedule and customer disclosures.$q$, deliverable=$q$Applicable pricing policy, fee schedule or customer pricing disclosure.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 4(3)(g), PDF p.8", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "National Payment Systems (Consumer Protection) Regulations, 2022 — Reg. 14, PDF p.12", "url": "https://drive.google.com/file/d/1I0n23-tnJSbwjLnT2mG1tioXWxpgIn8w/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 25, PDF p.8", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$pricing$q$, product_config=$q${}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$A05$q$;
update licence_application_templates set
  card_title=$q$Merchant / agent agreements$q$, card_note=$q$Add the applicable merchant or agent agreements.$q$, short_cta=$q$Add agreements$q$,
  guidance_long=$q$Where the payment-instrument model uses merchants or agents, the relevant merchant or agent agreement should be included with the application. The agreement should reflect the actual commercial and operating relationship. Where a PSO or PSP uses agents, the separate agent-approval requirements should be handled through the applicable agent workflow.$q$, deliverable=$q$Applicable merchant and / or agent agreement(s).$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 4(3)(e), PDF p.8", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$multi_upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf,.rtf,.txt"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$A06$q$;
update licence_application_templates set
  card_title=$q$Charge-recovery agreement$q$, card_note=$q$Upload the executed charge-recovery agreement.$q$, short_cta=$q$Upload agreement$q$,
  guidance_long=$q$The charge-recovery agreement should authorise the nominated financial institution to enable recovery of the applicable regulatory charges, fees and penalties. The executed agreement should clearly identify the applicant and the relevant financial institution and should support direct recovery as required.$q$, deliverable=$q$Executed charge-recovery agreement.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(w), PDF p.7", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 24, PDF p.8", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$upload$q$, product_config=$q${"accept": ".doc,.docx,.pdf"}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$S01$q$;
update licence_application_templates set
  card_title=$q$Foreign licences$q$, card_note=$q$Add each similar foreign licence held by the applicant.$q$, short_cta=$q$Add foreign licence$q$,
  guidance_long=$q$The applicant should disclose each country in which it holds a licence to conduct the same or similar payment activity and provide a copy of the licence. The disclosure should identify the country, regulator or licensing authority, licence type and current status. If there are no such foreign licences, that should be stated clearly.$q$, deliverable=$q$List of applicable foreign licences with copies of each licence, or a confirmed 'none' response.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(x), PDF p.7", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 24, PDF p.8", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$foreign_licences$q$, product_config=$q${}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$S02$q$;
update licence_application_templates set
  card_title=$q$Application fee$q$, card_note=$q$Upload proof of payment of the application fee.$q$, short_cta=$q$Upload proof of payment$q$,
  guidance_long=$q$The applicable application fee should be paid and proof of payment should be included with the application. The payment evidence should clearly identify the payment and be capable of being matched to the applicant and the licence application. Where the applicable application fee is nil, no payment evidence should be requested.$q$, deliverable=$q$Proof of payment of the applicable application fee. No upload where the fee is nil.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(2)(r), PDF p.6", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 19, PDF p.7", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}, {"text": "National Payment Systems (Amendment) Regulations, 2022 — Schedule 3, PDF pp.2–4", "url": "https://drive.google.com/file/d/1oozJCdTwoyvU_kRJHpiHBi_ZxWqG2sCY/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$fee_proof$q$, product_config=$q${}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$S03$q$;
update licence_application_templates set
  card_title=$q$Final application pack$q$, card_note=NULL, short_cta=NULL,
  guidance_long=$q$The final application should contain the prescribed application form, covering letter and every supporting document that applies to the selected licence route. Before submission, the applicant details, licence category and class, people, financial figures, fees and supporting documents should be consistent, and only the current final versions should be included in the pack.$q$, deliverable=$q$No separate upload. Beacon should assemble the final application pack from the current final versions of the applicable forms and documents.$q$,
  sources=$q$[{"text": "BoU NPS Licensing FAQs, 2022 — Q13, PDF p.3", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}, {"text": "NPS Application Forms, 2021 — Form A supporting documents, PDF p.2", "url": "https://drive.google.com/file/d/1ig6A2a8Cvfmm2Qgr7cVgxBmSzgh7Bp_b/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$system$q$, product_config=$q${}$q$::jsonb, workspace_hidden=true
where application_key='payments_nps' and external_id=$q$S05$q$;
update licence_application_templates set
  card_title=$q$BoU information request$q$, card_note=NULL, short_cta=NULL,
  guidance_long=$q$Where additional or missing information is requested during evaluation, the response should address the request completely and remain consistent with the application already submitted. Any replacement or updated document should be clearly identified so that the response can be linked to the relevant requirement and submission version.$q$, deliverable=$q$Response to the specific information request, including any updated or replacement documents.$q$,
  sources=$q$[{"text": "BoU NPS Licensing FAQs, 2022 — Q11, PDF p.2", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$event$q$, product_config=$q${}$q$::jsonb, workspace_hidden=true
where application_key='payments_nps' and external_id=$q$S06$q$;
update licence_application_templates set
  card_title=$q$Vetting & premises readiness$q$, card_note=NULL, short_cta=NULL,
  guidance_long=$q$The applicant should be ready for the fit-and-proper vetting process and for inspection of its business premises before the licence is granted. The relevant people should be available to support the vetting process, current or original documents should be available where requested, and the premises should be in the condition represented in the application.$q$, deliverable=$q$No new duplicate document pack. All outstanding vetting and premises-readiness items should be resolved.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(3), PDF p.7", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "BoU NPS Licensing FAQs, 2022 — Annex 1 item 4, PDF p.4", "url": "https://drive.google.com/file/d/1N3KPi9K00srJyaCM7yElcs7RyirjjE0c/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$aggregate$q$, product_config=$q${}$q$::jsonb, workspace_hidden=true
where application_key='payments_nps' and external_id=$q$S07$q$;
update licence_application_templates set
  card_title=$q$Licence fee$q$, card_note=NULL, short_cta=NULL,
  guidance_long=$q$Once a decision has been made to grant the licence, the applicable licence fee should be paid before the licensing process is completed. The amount should be based on the approved licence class or classes and the applicable Schedule 3 fee.$q$, deliverable=$q$Proof of payment of the applicable licence fee after the grant decision.$q$,
  sources=$q$[{"text": "National Payment Systems Regulations, 2021 — Reg. 3(5), PDF p.7", "url": "https://drive.google.com/file/d/1zWo5-Js9kYXuZmQCTYZCQrJNQI__YpJh/view?usp=drivesdk"}, {"text": "National Payment Systems (Amendment) Regulations, 2022 — Schedule 3, PDF pp.2–4", "url": "https://drive.google.com/file/d/1oozJCdTwoyvU_kRJHpiHBi_ZxWqG2sCY/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$event$q$, product_config=$q${}$q$::jsonb, workspace_hidden=true
where application_key='payments_nps' and external_id=$q$L01$q$;
update licence_application_templates set
  card_title=$q$Uganda primary data centre$q$, card_note=$q$Record the Uganda primary data-centre arrangement and supporting evidence.$q$, short_cta=$q$Add data-centre arrangement$q$,
  guidance_long=$q$An electronic money issuer should establish and maintain the primary data centre supporting its payment services in Uganda. The application should be able to demonstrate the Uganda location and the hosting or architecture arrangement supporting that requirement.$q$, deliverable=$q$Evidence demonstrating the Uganda primary-data-centre location and the relevant hosting / architecture arrangement.$q$,
  sources=$q$[{"text": "National Payment Systems Act, 2020 (Cap. 59) — s.68, PDF p.28", "url": "https://drive.google.com/file/d/1TssAB7TOnkqpUjWWHs8dzWxteSlsU7AM/view?usp=drivesdk"}]$q$::jsonb, official_form=NULL,
  product_type=$q$data_centre$q$, product_config=$q${}$q$::jsonb, workspace_hidden=false
where application_key='payments_nps' and external_id=$q$L07$q$;
commit;
