// Snapshot of the published Apply catalogue (licence_application_templates, wizard classes and fee tiers)
// as read from the live database. Used only to give the admin demonstration realistic sample data.
export type TemplateRow = [id: string, phase: string, title: string, drawer: string, route: string];
export type ClassRow = [app: string, key: string, label: string, minCapital: number | null];
export type FeeRow = [app: string, classKey: string, type: "application" | "licensing" | "annual", amount: number];

export const TEMPLATES: Record<"payments_nps" | "digital_lending" | "insurance", TemplateRow[]> = {
  digital_lending: [
    ["ML-A1", "business", "Company registration & tax documents", "company_registration", "ml"],
    ["ML-A3", "business", "Business address & operating area", "premises", "ml"],
    ["NDT-A1", "business", "Institution registration & legal form", "company_registration", "ndt"],
    ["NDT-A2", "business", "Management & administrative structure", "org_structure", "ndt"],
    ["NDT-A3", "business", "Head office, places of business & operating history", "premises", "ndt"],
    ["NDT-A6", "business", "Capital, bankers & auditor", "capital", "ndt"],
    ["ML-S1", "finalise", "Application fee", "generic_upload", "ml"],
    ["ML-S2", "finalise", "Money Lender Form 1", "official_form", "ml"],
    ["NDT-S1", "finalise", "Application fee", "generic_upload", "ndt"],
    ["NDT-S2", "finalise", "NDTMFI Form 1A & declaration", "official_form", "ndt"],
    ["ML-A2", "people", "Directors & company secretary", "people", "ml"],
    ["NDT-A4", "people", "Board & senior management", "people", "ndt"],
    ["NDT-A5", "people", "Institution history & related-party disclosures", "declarations", "ndt"],
    ["DL-A7", "policies", "AML/CFT framework", "generic_upload", ""],
    ["DL-A8", "policies", "Data protection policy & PDPO Certificate of Registration", "data_protection", ""],
    ["DL-A9", "policies", "Credit policy", "generic_upload", ""],
    ["DL-A10", "policies", "Governance, ethics & market conduct", "governance", ""],
    ["DL-A2", "products", "Loan products, terms & pricing", "product_desc", ""],
    ["DL-A3", "products", "Source of funds", "source_funds", ""],
    ["DL-A4", "products", "Template lending agreement", "lending_agreement", ""],
    ["DL-A5", "technology", "ICT system & digital delivery channels", "it_controls", ""],
  ],
  insurance: [
    ["INS-B1", "business", "Share capital", "capital", ""],
    ["INS-B2", "business", "Statutory security deposit", "financials", "insurer"],
    ["INS-B3", "business", "Government-securities deposit (brokers)", "financials", "broker"],
    ["INS-B4", "business", "Net worth & composition of capital", "financials", ""],
    ["INS-B5", "business", "Reinsurance / retrocession arrangements", "repeat_arrangement", "insurer"],
    ["INS-B6", "business", "Business plan & 3-year feasibility study", "docpack", ""],
    ["INS-B7", "business", "Audited financial statements", "generic_upload", ""],
    ["INS-B8", "business", "Bankers & auditors", "multi_upload", ""],
    ["INS-B9", "business", "Professional indemnity insurance", "generic_upload", ""],
    ["INS-C1", "company", "Company registration & legal status", "company_registration", ""],
    ["INS-C2", "company", "Head office & branch addresses", "premises", ""],
    ["INS-C3", "company", "Nature of business & commencement date", "product_desc", ""],
    ["INS-C4", "company", "Registration fee", "fee_proof", ""],
    ["INS-C5", "company", "TIN & tax registration", "tin_tax", ""],
    ["INS-CP1", "compliance", "AML/CFT risk-assessment framework", "generic_upload", ""],
    ["INS-CP2", "compliance", "Dispute-resolution clause in contracts", "customer_terms", ""],
    ["INS-CP3", "compliance", "Policy / contract specimens & rating scales", "docpack", ""],
    ["INS-CP4", "compliance", "Pre-insurance risk survey procedures", "generic_upload", "insurer"],
    ["INS-CP5", "compliance", "Member benefit packages & premiums", "pricing", "hmo"],
    ["INS-CP6", "compliance", "Customer data protection", "data_protection", ""],
    ["INS-CP7", "compliance", "Insurance Institute / Training College membership", "generic_upload", ""],
    ["INS-F1", "forms", "IRA registration form (Form 3B)", "official_form", ""],
    ["INS-F2", "forms", "Licence application form", "official_form", ""],
    ["INS-F3", "forms", "Licence fee", "fee_proof", ""],
    ["INS-F4", "forms", "Personal questionnaire forms", "multi_upload", ""],
    ["INS-F5", "forms", "CEO declaration & certification", "declarations", ""],
    ["INS-P1", "people", "Directors — details & CVs", "people", ""],
    ["INS-P2", "people", "Shareholders & ownership structure", "ownership", ""],
    ["INS-P3", "people", "Senior executive & key management", "org_structure", ""],
    ["INS-P4", "people", "Fit-and-proper declarations", "declarations", ""],
    ["INS-P5", "people", "Agency agreement & Certificate of Competency", "governance", "agent"],
    ["INS-P6", "people", "Medical Director / head of health services", "generic_upload", "hmo"],
    ["INS-R1", "review", "Confirm application completeness", "declarations", ""],
    ["INS-R2", "review", "Authority Technical Committee & Board review", "generic_upload", ""],
    ["INS-R3", "review", "Post-approval obligations", "governance", ""],
    ["INS-T1", "technology", "Appointed actuary", "people", "insurer"],
    ["INS-T2", "technology", "Risk, compliance & internal audit functions", "org_structure", ""],
    ["INS-T3", "technology", "Outsourcing & affiliate arrangements", "repeat_arrangement", ""],
    ["INS-T4", "technology", "Agents & distribution network", "multi_upload", ""],
    ["INS-T5", "technology", "Regulatory reporting systems readiness", "it_controls", ""],
  ],
  payments_nps: [
    ["B01", "business", "Prepare the product and operations description", "product_desc", ""],
    ["B02", "business", "Prepare the payment-instrument description", "product_desc", "instrument"],
    ["B03", "business", "Prepare the three-year business plan and financial projections", "financials", ""],
    ["B04", "business", "Prepare the organisation, governance and management structure", "org_structure", ""],
    ["B06", "business", "Prepare historical or pre-trading financial statements", "financials", ""],
    ["B07", "business", "Evidence the applicable minimum paid-up capital", "capital", ""],
    ["B09", "business", "Provide the company TIN and tax-clearance certificate", "tin_tax", ""],
    ["B10", "business", "Prepare the finance policy", "generic_upload", ""],
    ["B11", "business", "Prepare the HR policy", "generic_upload", ""],
    ["C01", "company", "Confirm the applicant entity is eligible", "company_registration", ""],
    ["C02", "company", "Prepare the company incorporation pack", "company_registration", "pso"],
    ["C03", "company", "Align the company objects with the licensed activities", "company_registration", "pso"],
    ["C04", "company", "Reflect BoU approval requirements for shareholding changes", "ownership", ""],
    ["C05", "company", "Obtain the board resolution authorising the application", "generic_upload", ""],
    ["C06", "company", "Prepare foreign corporate shareholder documents", "ownership", ""],
    ["C07", "company", "Secure suitable business premises", "premises", ""],
    ["G01", "company", "Demonstrate payment-system interoperability", "product_desc", "pso"],
    ["G03", "company", "Establish the correct EMI legal entity", "emi_structure", "emi"],
    ["F01", "forms", "Prepare the covering letter", "generic_upload", ""],
    ["F02", "forms", "Complete and commission Form A", "official_form", "pso"],
    ["F03", "forms", "Complete and commission Form C", "official_form", "instrument"],
    ["F04", "forms", "Complete Form B for each person being vetted", "people", ""],
    ["G02", "forms", "Attach the existing PSP or PSO licence where applicable", "generic_upload", "instrument"],
    ["S01", "forms", "Execute the charge-recovery agreement", "generic_upload", ""],
    ["S02", "forms", "List licences held in other countries", "multi_upload", ""],
    ["S03", "forms", "Pay the application fee and attach proof", "fee_proof", ""],
    ["S05", "forms", "Submit the complete application", "generic_upload", ""],
    ["P01", "people", "Map the ownership and beneficial-ownership structure", "ownership", ""],
    ["P02", "people", "Prepare the directors and senior-management schedule", "people", ""],
    ["P03", "people", "Prepare detailed CVs", "people", ""],
    ["P04", "people", "Prepare proof of identity and passport photographs", "people", ""],
    ["P05", "people", "Obtain certificates of good conduct", "people", ""],
    ["P06", "people", "Obtain credit-reference reports", "credit", ""],
    ["P07", "people", "Obtain personal tax-clearance evidence", "tin_tax", ""],
    ["P08", "people", "Prepare two recommendation letters for each eligible person", "people", ""],
    ["P09", "people", "Prepare source-of-funds evidence", "source_funds", ""],
    ["P10", "people", "Prepare work permits for foreign resident directors and senior managers", "people", ""],
    ["A01", "policies", "Prepare the AML/CFT policy", "generic_upload", ""],
    ["A02", "policies", "Prepare the consumer-protection policy", "generic_upload", ""],
    ["A03", "policies", "Prepare customer disclosure, complaints and redress procedures", "generic_upload", ""],
    ["A04", "policies", "Prepare customer terms or service agreement", "customer_terms", "emi"],
    ["A05", "policies", "Prepare the pricing and fee disclosure", "pricing", "instrument"],
    ["A06", "policies", "Prepare merchant or agent agreements where applicable", "repeat_arrangement", "instrument"],
    ["S06", "review", "Respond to BoU information requests", "generic_upload", ""],
    ["S07", "review", "Prepare for BoU vetting and premises inspection", "premises", ""],
    ["L01", "review", "Pay the licence fee after approval", "fee_proof", "pso"],
    ["L07", "review", "Establish the primary data centre in Uganda", "data_centre", "emi"],
    ["T01", "technology", "Prepare the risk-management framework", "generic_upload", "instrument"],
    ["T02", "technology", "Prepare the disaster-recovery plan", "it_controls", ""],
    ["T03", "technology", "Prepare the business-continuity plan", "it_controls", ""],
    ["T04", "technology", "Prepare the cybersecurity plan and policy", "it_controls", ""],
    ["T05", "technology", "Prepare the data-protection and privacy policy", "data_protection", ""],
    ["T06", "technology", "Prepare the IT policy and control documentation", "it_controls", ""],
    ["T07", "technology", "Complete pre-application penetration testing", "pentest", ""],
    ["T08", "technology", "Provide the required NITA-U systems-licence evidence", "it_controls", ""],
    ["T09", "technology", "Prepare outsourcing arrangements", "repeat_arrangement", ""],
    ["T10", "technology", "Document participation in other payment systems", "repeat_arrangement", ""],
    ["T11", "technology", "Prepare payment-system rules", "docpack", "pso"],
  ],
};

export const CLASSES: ClassRow[] = [
  ["digital_lending", "ml", "Money Lender", null],
  ["digital_lending", "ndt", "Non-Deposit-Taking MFI (NDTMFI)", null],
  ["insurance", "insurer_life", "Insurer — Life Business", 4500000000],
  ["insurance", "insurer_nonlife", "Insurer — Non-Life Business", 6000000000],
  ["insurance", "reinsurer_life", "Reinsurer — Life Business", 6000000000],
  ["insurance", "reinsurer_nonlife", "Reinsurer — Non-Life Business", 9000000000],
  ["insurance", "broker_insurance", "Insurance Broker", 75000000],
  ["insurance", "broker_reinsurance", "Reinsurance Broker", 75000000],
  ["insurance", "agent_individual", "Insurance Agent — Individual", null],
  ["insurance", "agent_corporate", "Insurance Agent — Corporate Agency", null],
  ["insurance", "hmo", "Health Membership Organisation (HMO)", null],
  ["payments_nps", "pso_funds_transfer_large", "PSO — Funds transfer system (large)", 1000000000],
  ["payments_nps", "pso_funds_transfer_medium", "PSO — Funds transfer system (medium)", 500000000],
  ["payments_nps", "pso_funds_transfer_small", "PSO — Funds transfer system (small)", 100000000],
  ["payments_nps", "pso_clearing_switch", "PSO — Clearing system or switch", 500000000],
  ["payments_nps", "pso_settlement", "PSO — Settlement system", 250000000],
  ["payments_nps", "pso_third_party", "PSO — Third-party system", 100000000],
  ["payments_nps", "psp_emi_large", "PSP — Electronic-money issuer (large)", 10000000000],
  ["payments_nps", "psp_emi_medium_100bn", "PSP — Electronic-money issuer (medium, up to 100bn)", 5000000000],
  ["payments_nps", "psp_emi_medium_50bn", "PSP — Electronic-money issuer (medium, up to 50bn)", 2000000000],
  ["payments_nps", "psp_emi_medium_5bn", "PSP — Electronic-money issuer (medium, up to 5bn)", 1000000000],
  ["payments_nps", "psp_emi_small_500m", "PSP — Electronic-money issuer (small, up to 500m)", 250000000],
  ["payments_nps", "psp_emi_small_250m", "PSP — Electronic-money issuer (small, up to 250m)", 100000000],
  ["payments_nps", "psp_other", "PSP — Any other PSP", 100000000],
  ["payments_nps", "instrument", "Payment instrument issuer — cards, electronic devices or paper instruments", 0],
];

export const FEES: FeeRow[] = [
  ["digital_lending", "ml", "application", 50000],
  ["digital_lending", "ndt", "application", 50000],
  ["insurance", "insurer_life", "application", 1000000],
  ["insurance", "insurer_life", "licensing", 4000000],
  ["insurance", "insurer_nonlife", "application", 1000000],
  ["insurance", "insurer_nonlife", "licensing", 4000000],
  ["insurance", "reinsurer_life", "application", 1000000],
  ["insurance", "reinsurer_life", "licensing", 10000000],
  ["insurance", "reinsurer_nonlife", "application", 1000000],
  ["insurance", "reinsurer_nonlife", "licensing", 10000000],
  ["insurance", "broker_insurance", "application", 500000],
  ["insurance", "broker_insurance", "licensing", 1000000],
  ["insurance", "broker_reinsurance", "application", 800000],
  ["insurance", "broker_reinsurance", "licensing", 1000000],
  ["insurance", "agent_individual", "licensing", 100000],
  ["insurance", "agent_corporate", "licensing", 200000],
  ["insurance", "hmo", "application", 500000],
  ["insurance", "hmo", "licensing", 3000000],
  ["payments_nps", "pso_funds_transfer_large", "application", 3000000],
  ["payments_nps", "pso_funds_transfer_large", "licensing", 25000000],
  ["payments_nps", "pso_funds_transfer_large", "annual", 25000000],
  ["payments_nps", "pso_funds_transfer_medium", "application", 3000000],
  ["payments_nps", "pso_funds_transfer_medium", "licensing", 20000000],
  ["payments_nps", "pso_funds_transfer_medium", "annual", 20000000],
  ["payments_nps", "pso_funds_transfer_small", "application", 3000000],
  ["payments_nps", "pso_funds_transfer_small", "licensing", 15000000],
  ["payments_nps", "pso_funds_transfer_small", "annual", 15000000],
  ["payments_nps", "pso_clearing_switch", "application", 3000000],
  ["payments_nps", "pso_clearing_switch", "licensing", 25000000],
  ["payments_nps", "pso_clearing_switch", "annual", 25000000],
  ["payments_nps", "pso_settlement", "application", 3000000],
  ["payments_nps", "pso_settlement", "licensing", 25000000],
  ["payments_nps", "pso_settlement", "annual", 25000000],
  ["payments_nps", "pso_third_party", "application", 3000000],
  ["payments_nps", "pso_third_party", "licensing", 10000000],
  ["payments_nps", "pso_third_party", "annual", 10000000],
  ["payments_nps", "psp_emi_large", "application", 3000000],
  ["payments_nps", "psp_emi_large", "licensing", 25000000],
  ["payments_nps", "psp_emi_large", "annual", 25000000],
  ["payments_nps", "psp_emi_medium_100bn", "application", 3000000],
  ["payments_nps", "psp_emi_medium_100bn", "licensing", 20000000],
  ["payments_nps", "psp_emi_medium_100bn", "annual", 20000000],
  ["payments_nps", "psp_emi_medium_50bn", "application", 3000000],
  ["payments_nps", "psp_emi_medium_50bn", "licensing", 18000000],
  ["payments_nps", "psp_emi_medium_50bn", "annual", 18000000],
  ["payments_nps", "psp_emi_medium_5bn", "application", 3000000],
  ["payments_nps", "psp_emi_medium_5bn", "licensing", 16000000],
  ["payments_nps", "psp_emi_medium_5bn", "annual", 16000000],
  ["payments_nps", "psp_emi_small_500m", "application", 3000000],
  ["payments_nps", "psp_emi_small_500m", "licensing", 15000000],
  ["payments_nps", "psp_emi_small_500m", "annual", 15000000],
  ["payments_nps", "psp_emi_small_250m", "application", 3000000],
  ["payments_nps", "psp_emi_small_250m", "licensing", 10000000],
  ["payments_nps", "psp_emi_small_250m", "annual", 10000000],
  ["payments_nps", "psp_other", "application", 3000000],
  ["payments_nps", "psp_other", "licensing", 10000000],
  ["payments_nps", "psp_other", "annual", 10000000],
  ["payments_nps", "instrument", "application", 0],
  ["payments_nps", "instrument", "licensing", 0],
  ["payments_nps", "instrument", "annual", 0],
];

// Insurance Comply catalogue as held in the database (21 obligations). Flags decide the audience.
export type InsRow = [id: string, title: string, group: string, type: string, source: string, guidance: string, evidence: string, flags: string];
export const INSURANCE_OBLIGATIONS: InsRow[] = [
  ["CAP-01", "Maintain minimum paid-up capital for your licensed class", "Capital & Solvency", "Continuous prudential control", "", "UGX 4,500,000,000 (life) / 6,000,000,000 (non-life) / 6,000,000,000 (reinsurance-life) / 9,000,000,000 (reinsurance-non-life).", "Audited capital / net-worth statement", "insurer"],
  ["CAP-02", "Maintain the statutory security deposit under IRA's lien", "Capital & Solvency", "Continuous prudential control", "Section 38, Insurance Act 2017; Regulations 16 & 17, Insurance (Capital Adequacy and Prudential Requirements) Regulations, 2020", "At least 10% of the prescribed paid-up capital, invested in Government Securities or Authority-approved investments.", "Deposit statement from the holding bank, IRA lien confirmation", "insurer"],
  ["CAP-03", "Maintain minimum paid-up capital (Insurance/Reinsurance Brokers)", "Capital & Solvency", "Continuous prudential control", "", "At least UGX 75,000,000, of which UGX 19,000,000 invested in Government securities under the Authority's lien.", "Audited capital statement", "broker"],
  ["CAP-04", "Maintain professional indemnity insurance cover", "Capital & Solvency", "Continuous prudential control", "", "At least UGX 100,000,000.", "Current PI insurance policy / certificate", "broker,hmo"],
  ["GOV-01", "Refresh director / senior-officer / significant-shareholder fit-and-proper questionnaires", "Governance & Fit-and-Proper", "Recurring governance control", "", "Covers each Director, Senior Officer, Principal Officer and Significant Shareholder.", "Completed personal questionnaire forms", "insurer"],
  ["GOV-02", "Maintain fit-and-proper standing for directors and senior staff", "Governance & Fit-and-Proper", "Continuous governance control", "", "No conviction for fraud/dishonesty, no bankruptcy/composition with creditors, no involvement managing a wound-up insurance or financial institution in the last 5 years.", "Declarations on file; disclosure record of any disqualifying event", "all"],
  ["GOV-03", "Keep agent Certificate of Competency and agency agreement current", "Governance & Fit-and-Proper", "Continuous control", "", "Certificate of Competency signed by the Principal Officer of the insurer the agent represents.", "Signed Certificate of Competency, agency agreement", "agent"],
  ["LIC-01", "Renew the Insurance/Reinsurance Broker licence", "Licensing & Renewal", "Recurring licence renewal", "§2.3", "A compliance fee of UGX 1,000,000 is listed among the enclosures and is reasonably read as payable with each renewal.", "Renewal application, compliance fee payment evidence", "broker"],
  ["MEM-01", "Maintain membership of the Insurance Institute of Uganda", "Industry Membership & Levies", "Continuous membership control", "", "", "Current membership certificate / receipt", "insurer,broker,hmo"],
  ["MEM-02", "Maintain membership of the Insurance Training College of Uganda", "Industry Membership & Levies", "Continuous membership control", "", "", "Current membership evidence", "insurer,broker"],
  ["MEM-03", "Pay the quarterly training levy to the Insurance Institute of Uganda", "Industry Membership & Levies", "Recurring statutory payment", "§4.0", "0.5% levy; the basis the percentage is applied to is not specified in the source guideline.", "Levy payment receipt", "hmo"],
  ["MEM-04", "Pay the IRA annual contribution", "Industry Membership & Levies", "Recurring statutory payment", "§3.0", "Amount is set by the IRA and is not fixed in the source guideline.", "Payment receipt", "hmo"],
  ["OPS-01", "Keep expatriate staff work permits valid", "Risk & Operations", "Continuous control", "(x)", "", "Valid work permits on file", "hmo"],
  ["OPS-02", "Keep service-provider / affiliate contracts current and on file", "Risk & Operations", "Continuous control", "(xi)", "", "Signed service-provider / affiliate contracts", "hmo"],
  ["OPS-03", "Keep the Medical Director's registration current", "Risk & Operations", "Continuous control", "(xvi)", "", "Current registration certificate from the Uganda Medical and Dental Practitioners' Council", "hmo"],
  ["RPT-01", "Submit audited annual accounts to the IRA", "Reporting & Accounts", "Recurring regulatory return", "Insurer/Reinsurer application-form items on accounts submission; HMO guideline (iv)", "No fixed day-count is stated for Insurers/Reinsurers/Brokers in the source guideline beyond 'date set by the Authority'.", "Audited annual accounts, auditor's report, IRA submission receipt", "insurer,broker,hmo"],
  ["RPT-02", "File quarterly management accounts", "Reporting & Accounts", "Recurring regulatory return", "HMO guideline (v)", "", "Quarterly management accounts, IRA submission receipt", "hmo"],
  ["RPT-03", "Hold the Annual General Meeting and submit the minutes to IRA", "Reporting & Accounts", "Recurring governance filing", "Application-form items on AGM date and minutes submission", "", "AGM notice, signed minutes, IRA submission receipt", "insurer"],
  ["RPT-04", "Submit the actuarial valuation and valuation report", "Reporting & Accounts", "Recurring regulatory return", "", "Applies to insurers/reinsurers writing life business.", "Actuarial valuation report, IRA submission receipt", "insurer,life"],
  ["RPT-05", "Submit annual reinsurance / retrocession arrangement details", "Reporting & Accounts", "Recurring regulatory return", "Section 67, Insurance Act 2017; Insurance (Reinsurance) Regulations, 2020", "", "Reinsurance/retrocession treaty summary, IRA submission receipt", "insurer,nonlife"],
  ["RPT-06", "File the Mutual Insurance Company annual licensing return (Form 2)", "Reporting & Accounts", "Recurring regulatory filing", "Reg. 5(1) & Sec. 9, Form 2; Reg. 5(2), Form 2A", "Applies specifically to insurers registered as a Mutual Insurance Company, not every Insurer/Reinsurer licensee.", "Completed Form 2/2A, CVs, feasibility update, latest cash flow/balance sheet/P&L/revenue account", "insurer"],
];
